# Generated by Django 4.0.6 on 2022-07-22 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('target_date', models.DateTimeField()),
                ('complete', models.BooleanField()),
                ('complete_date', models.BooleanField()),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='images/%Y/%m/%d')),
            ],
        ),
    ]
