# Generated by Django 4.0.6 on 2022-07-22 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='complete_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='target_date',
            field=models.DateTimeField(null=True),
        ),
    ]
